export { default as Expression } from "./Expression";
export { default as GeneAssignments } from "./GeneAssignments";
export { default as GOTerms } from "./GOTerms";
export { default as Pathways } from "./Pathways";
export { default as ProteinDomains } from "./ProteinDomains";
export { default as RNAAssignments } from "./RNAAssignments";
export { default as SwissProt } from "./SwissProt";
export { default as TissueExpression } from "./TissueExpression";
export { default as Unigene } from "./Unigene";
